
app:
  listener:
    directory: C:\Users\ersel.bora\Downloads\interview-assessment-mendix-developer\Recipes\Upload
  redis:
    host: localhost
    port: 6379
    recipeIndex: recipe
    categoryIndex: category
    